name: audioplayer_example
description: a audio player plugin example
version: 2.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  path_provider:
  http:
  audioplayer:
    path: ../audioplayer
  audioplayer_web:
    path: ../audioplayer_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
