name: audioplayer
description: A flutter plugin to play audio files
version: 0.6.0
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/audioplayer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: bz.rxla.audioplayer
        pluginClass: AudioplayerPlugin
      ios:
        pluginClass: AudioplayerPlugin
      macos:
        pluginClass: AudioplayerPlugin
